# permissions for end users to view waterheaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waterheater-viewer-role
rules:
- apiGroups:
  - demo.demo.appsflyer.com
  resources:
  - waterheaters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.demo.appsflyer.com
  resources:
  - waterheaters/status
  verbs:
  - get
